### create a new user
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "sample@email.com",
    "password": "test"
}

### sign in with user
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "sample@email.com",
    "password": "test"
}


### get current user info
GET http://localhost:3000/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoic2FtcGxlQGVtYWlsLmNvbSIsImlhdCI6MTcwMzUwMzQ3NCwiZXhwIjoxNzAzNTA0Mzc0fQ.CCEHcNTN62N91_sUaskrGExU-sy44rm1ietPKX76Ffw

### update current user info
Patch http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoic2FtcGxlQGVtYWlsLmNvbSIsImlhdCI6MTcwMzUwMzQ3NCwiZXhwIjoxNzAzNTA0Mzc0fQ.CCEHcNTN62N91_sUaskrGExU-sy44rm1ietPKX76Ffw
content-type: application/json

{
    "email": "sample@gmail.com",
    "password": "test"
}

